FROM python:3.6-alpine

WORKDIR /usr/src/app

COPY requirements.txt requirements.txt

RUN python -m venv venv
RUN venv/bin/pip install -r requirements.txt
RUN venv/bin/pip install gunicorn

COPY . .

RUN chmod +x boot.sh

ENV FLASK_APP microblog.py

EXPOSE 5000

ENTRYPOINT ["./boot.sh"]